/**
 * 方言點常數（單一來源，hardcode，不寫入數據庫）
 * 覆蓋廣東、廣西主要粵語方言點，香港繁體標籤。
 * 結構：地區（可帶括號）+ 下級地點，對應 Jyutjyu 等語料來源。
 */

export const DIALECT_IDS = [
  // 廣東 — 珠三角／粵中
  'guangzhou',
  'hongkong',
  'macau',
  'qingyuan',
  'qingxin',
  'nanhai_shatou',
  'panyu_nansha',
  'foshan',
  'shunde',
  'zhongshan',
  'zhongshan_xiaolan',
  'zhongshan_shiqi',
  'sanshui',
  // 肇慶一帶
  'duanzhou',
  'dinghu_pucao',
  'zhaoqing',
  'sihui',
  'guangning',
  'huaiji_huaicheng',
  'huaiji_lengkeng',
  'fengkai_kaijian',
  'deqing',
  'fengkai_fengchuan',
  // 江門五邑
  'jiangmen',
  'jiangmen_shuinan',
  'jiangmen_xuding',
  'jiangmen_beijie',
  'jiangmen_hetang',
  'jiangmen_danzao',
  'jiangmen_huangzhuang',
  'jiangmen_mayuan',
  'xinhui',
  'xinhui_huicheng',
  'xinhui_siqian',
  'xinhui_tianhu',
  'xinhui_luokeng',
  'taishan',
  'taishan_dajiang',
  'taishan_taicheng',
  'taishan_doushan',
  'kaiping',
  'kaiping_magang',
  'kaiping_chikan',
  'kaiping_cangcheng',
  'kaiping_changsha',
  'kaiping_shatang',
  'enping',
  'enping_encheng',
  'enping_jiangzhou',
  'heshan',
  'heshan_shaping',
  'heshan_longkou',
  'heshan_yayao',
  // 粵西／雲浮
  'xinxing',
  'yangchun_songbai',
  'yunan',
  'luoding',
  'luoding_chuanbu',
  'yunfu',
  // 梧州一帶（廣西東）
  'cangwu_shiqiao',
  'wuzhou',
  'wuzhou_rongxu',
  'wuzhou_fudian',
  'mengshan',
  'mengshan_chentang',
  'cenxi',
  // 桂東南
  'guiping',
  'guiping_danjia',
  'guiping_jintian',
  'guiping_jiangkou',
  'guiping_xunwang',
  'guiping_mugen',
  'pingnan',
  'xiangzhou',
  'xiangzhou_shilong',
  'guigang',
  'guigang_jieli',
  'xingye_shanxin',
  'bobai_shuiming',
  'yulin',
  'yulin_datang',
  'beiliu',
  'beiliu_liumadawang',
  'rongxian',
  'rongxian_shitou',
  'wudong',
  // 南寧一帶
  'xinxu',
  'yongning',
  'nanning',
  'nanning_tingzi',
  'hengxian',
  'hengzhou',
  'binyang',
  // 桂北／柳州一帶
  'yizhou',
  'rongshui',
  'rongan_changan',
  'sanjiang_guyi',
  'sanjiang_guyihuangpai',
  'sanjiang_chengcun',
  'yangshuo_xingpingxinganzhou',
  'lingui_wutong',
  'lingui_huangsha',
  // 桂西
  'baise_youjiang',
  'longzhou',
  'hekou',
  // 粵西 — 陽江、茂名、湛江
  'yangjiang',
  'yangchun_heshui',
  'yangchun_tanshui',
  'yangchun_shuangjiao',
  'yangchun_hekou',
  'yangdong',
  'maoming',
  'maoming_malan',
  'gaozhou',
  'suixi_suicheng',
  'suixi_caotan',
  'zhanjiang',
  'zhanjiang_potou',
  'wuchuan',
  'huazhou_xiajiang',
  'huazhou_shangjiang',
  // 桂南 — 北海、欽州、防城
  'beihai',
  'beihai_yingpan',
  'beihai_haibianhua',
  'qinzhou',
  'fangchenggang',
  'haining_hehui',
  'lingshan',
  'lingshan_taiping',
  'xiaojiang_fuwang',
  'pubei_fuwang',
  'lianzhou',
  'lianjiang_hailaohua',
  'sanya_maihua',
  'danzhou',
  // 東莞、珠海、深圳等
  'dongguan',
  'dongguan_tangjiao',
  'dongguan_huangmaling',
  'zhuhai',
  'zhuhai_doumen',
  'shenzhen',
  // 連南
  'liannan_zhaigang',
  // 韶關（原有）
  'shaoguan',
  // 賀州（原有）
  'hezhou',
  // 海外 — 北美
  'usa_san_francisco',
  'usa_new_york',
  'usa_los_angeles',
  'canada_vancouver',
  'canada_toronto',
  // 海外 — 澳洲、紐西蘭
  'australia_sydney',
  'australia_melbourne',
  'newzealand_auckland',
  // 海外 — 英國
  'uk_london',
  // 海外 — 東南亞
  'singapore',
  'malaysia_kualalumpur',
  'malaysia_penang',
  'vietnam_hochiminh',
  'thailand_bangkok',
  // 其他
  'other'
] as const

export type DialectId = (typeof DIALECT_IDS)[number]

/** 方言代碼 → 顯示名稱（香港繁體） */
export const DIALECT_LABELS: Record<DialectId, string> = {
  guangzhou: '廣州',
  hongkong: '香港',
  macau: '澳門',
  qingyuan: '清遠',
  qingxin: '清新',
  nanhai_shatou: '南海 沙頭',
  panyu_nansha: '番禺 南沙',
  foshan: '佛山',
  shunde: '順德',
  zhongshan: '中山',
  zhongshan_xiaolan: '中山 小欖',
  zhongshan_shiqi: '中山 石岐',
  sanshui: '三水',
  duanzhou: '端州',
  dinghu_pucao: '鼎湖 甫草',
  zhaoqing: '肇慶',
  sihui: '四會',
  guangning: '廣寧',
  huaiji_huaicheng: '懷集 懷城',
  huaiji_lengkeng: '懷集 冷坑',
  fengkai_kaijian: '封開 開建',
  deqing: '德慶',
  fengkai_fengchuan: '封開 封川',
  jiangmen: '江門',
  jiangmen_shuinan: '江門 水南',
  jiangmen_xuding: '江門 墟頂',
  jiangmen_beijie: '江門 北街',
  jiangmen_hetang: '江門 荷塘',
  jiangmen_danzao: '江門 丹灶',
  jiangmen_huangzhuang: '江門 篁莊',
  jiangmen_mayuan: '江門 麻園',
  xinhui: '新會',
  xinhui_huicheng: '新會 會城',
  xinhui_siqian: '新會 司前',
  xinhui_tianhu: '新會 天湖',
  xinhui_luokeng: '新會 羅坑',
  taishan: '台山',
  taishan_dajiang: '台山 大江',
  taishan_taicheng: '台山 台城',
  taishan_doushan: '台山 斗山',
  kaiping: '開平',
  kaiping_magang: '開平 馬岡',
  kaiping_chikan: '開平 赤墈',
  kaiping_cangcheng: '開平 蒼城',
  kaiping_changsha: '開平 長沙',
  kaiping_shatang: '開平 沙塘',
  enping: '恩平',
  enping_encheng: '恩平 恩城',
  enping_jiangzhou: '恩平 江洲',
  heshan: '鶴山',
  heshan_shaping: '鶴山 沙坪',
  heshan_longkou: '鶴山 龍口',
  heshan_yayao: '鶴山 雅瑤',
  xinxing: '新興',
  yangchun_songbai: '陽春 松柏',
  yunan: '鬱南',
  luoding: '羅定',
  luoding_chuanbu: '羅定 船步',
  yunfu: '雲浮',
  cangwu_shiqiao: '蒼梧 石橋',
  wuzhou: '梧州',
  wuzhou_rongxu: '梧州 戎墟',
  wuzhou_fudian: '梧州 扶典',
  mengshan: '蒙山',
  mengshan_chentang: '蒙山 陳塘',
  cenxi: '岑溪',
  guiping: '桂平',
  guiping_danjia: '桂平 疍家',
  guiping_jintian: '桂平 金田',
  guiping_jiangkou: '桂平 江口',
  guiping_xunwang: '桂平 尋旺',
  guiping_mugen: '桂平 木根',
  pingnan: '平南',
  xiangzhou: '象州',
  xiangzhou_shilong: '象州 石龍',
  guigang: '貴港',
  guigang_jieli: '貴港 街里',
  xingye_shanxin: '興業 山心',
  bobai_shuiming: '博白 水鳴',
  yulin: '鬱林',
  yulin_datang: '鬱林 大塘',
  beiliu: '北流',
  beiliu_liumadawang: '北流 六麻大旺',
  rongxian: '容縣',
  rongxian_shitou: '容縣 石頭',
  wudong: '勿洞',
  xinxu: '心圩',
  yongning: '邕寧',
  nanning: '南寧',
  nanning_tingzi: '南寧 亭子',
  hengxian: '橫縣',
  hengzhou: '橫州',
  binyang: '賓陽',
  yizhou: '宜州',
  rongshui: '融水',
  rongan_changan: '融安 長安',
  sanjiang_guyi: '三江 古宜',
  sanjiang_guyihuangpai: '三江 古宜黃排',
  sanjiang_chengcun: '三江 程村',
  yangshuo_xingpingxinganzhou: '陽朔 興坪新嵅洲',
  lingui_wutong: '臨桂 五通',
  lingui_huangsha: '臨桂 黃沙',
  baise_youjiang: '百色 右江',
  longzhou: '龍州',
  hekou: '河口',
  yangjiang: '陽江',
  yangchun_heshui: '陽春 合水',
  yangchun_tanshui: '陽春 潭水',
  yangchun_shuangjiao: '陽春 雙滘',
  yangchun_hekou: '陽春 河口',
  yangdong: '陽東',
  maoming: '茂名',
  maoming_malan: '茂名 馬蘭',
  gaozhou: '高州',
  suixi_suicheng: '遂溪 遂城',
  suixi_caotan: '遂溪 草潭',
  zhanjiang: '湛江',
  zhanjiang_potou: '湛江 坡頭',
  wuchuan: '吳川',
  huazhou_xiajiang: '化州 下江',
  huazhou_shangjiang: '化州 上江',
  beihai: '北海',
  beihai_yingpan: '北海 營盤',
  beihai_haibianhua: '北海［海邊話］',
  qinzhou: '欽州',
  fangchenggang: '防城港',
  haining_hehui: '海寧 河檜',
  lingshan: '靈山',
  lingshan_taiping: '靈山 太平',
  xiaojiang_fuwang: '小江 福旺',
  pubei_fuwang: '浦北 福旺',
  lianzhou: '廉州',
  lianjiang_hailaohua: '廉江［海佬話］',
  sanya_maihua: '三亞［邁話］',
  danzhou: '儋州',
  dongguan: '東莞',
  dongguan_tangjiao: '東莞 塘角',
  dongguan_huangmaling: '東莞 黃麻嶺',
  zhuhai: '珠海',
  zhuhai_doumen: '珠海 斗門',
  shenzhen: '深圳',
  liannan_zhaigang: '連南 寨崗',
  shaoguan: '韶關',
  hezhou: '賀州',
  usa_san_francisco: '美國 三藩市',
  usa_new_york: '美國 紐約',
  usa_los_angeles: '美國 洛杉磯',
  canada_vancouver: '加拿大 溫哥華',
  canada_toronto: '加拿大 多倫多',
  australia_sydney: '澳洲 悉尼',
  australia_melbourne: '澳洲 墨爾本',
  newzealand_auckland: '紐西蘭 奧克蘭',
  uk_london: '英國 倫敦',
  singapore: '新加坡',
  malaysia_kualalumpur: '馬來西亞 吉隆坡',
  malaysia_penang: '馬來西亞 檳城',
  vietnam_hochiminh: '越南 胡志明市',
  thailand_bangkok: '泰國 曼谷',
  other: '其他'
}

/**
 * 方言代碼 → Jyutjyu 地區代碼（dialect.region_code）
 * 規則通常為地名拼音首字母大寫（如 廣州 GuangZhou → GZ），香港為 HK。
 */
export const DIALECT_REGION_CODES: Record<DialectId, string> = {
  guangzhou: 'GZ',
  hongkong: 'HK',
  macau: 'MO',
  qingyuan: 'QY',
  qingxin: 'QX',
  nanhai_shatou: 'NHST',
  panyu_nansha: 'PYNS',
  foshan: 'FS',
  shunde: 'SD',
  zhongshan: 'ZS',
  zhongshan_xiaolan: 'ZSXL',
  zhongshan_shiqi: 'ZSSQ',
  sanshui: 'SS',
  duanzhou: 'DZ',
  dinghu_pucao: 'DHPC',
  zhaoqing: 'ZQ',
  sihui: 'SH',
  guangning: 'GN',
  huaiji_huaicheng: 'HJHC',
  huaiji_lengkeng: 'HJLK',
  fengkai_kaijian: 'FKKJ',
  deqing: 'DQ',
  fengkai_fengchuan: 'FKFC',
  jiangmen: 'JM',
  jiangmen_shuinan: 'JMSN',
  jiangmen_xuding: 'JMXD',
  jiangmen_beijie: 'JMBJ',
  jiangmen_hetang: 'JMHT',
  jiangmen_danzao: 'JMDZ',
  jiangmen_huangzhuang: 'JMHZ',
  jiangmen_mayuan: 'JMMY',
  xinhui: 'XH',
  xinhui_huicheng: 'XHHC',
  xinhui_siqian: 'XHSQ',
  xinhui_tianhu: 'XHTH',
  xinhui_luokeng: 'XHLK',
  taishan: 'TS',
  taishan_dajiang: 'TSDJ',
  taishan_taicheng: 'TSTC',
  taishan_doushan: 'TSDS',
  kaiping: 'KP',
  kaiping_magang: 'KPMG',
  kaiping_chikan: 'KPCK',
  kaiping_cangcheng: 'KPCC',
  kaiping_changsha: 'KPCS',
  kaiping_shatang: 'KPST',
  enping: 'EP',
  enping_encheng: 'EPEC',
  enping_jiangzhou: 'EPJZ',
  heshan: 'HS',
  heshan_shaping: 'HSSP',
  heshan_longkou: 'HSLK',
  heshan_yayao: 'HSYY',
  xinxing: 'XX',
  yangchun_songbai: 'YCSB',
  yunan: 'YN',
  luoding: 'LD',
  luoding_chuanbu: 'LDCB',
  yunfu: 'YF',
  cangwu_shiqiao: 'CWSQ',
  wuzhou: 'WZ',
  wuzhou_rongxu: 'WZRX',
  wuzhou_fudian: 'WZFD',
  mengshan: 'MS',
  mengshan_chentang: 'MSCT',
  cenxi: 'CX',
  guiping: 'GP',
  guiping_danjia: 'GPDJ',
  guiping_jintian: 'GPJT',
  guiping_jiangkou: 'GPJK',
  guiping_xunwang: 'GPXW',
  guiping_mugen: 'GPMG',
  pingnan: 'PN',
  xiangzhou: 'XZ',
  xiangzhou_shilong: 'XZSL',
  guigang: 'GG',
  guigang_jieli: 'GGJL',
  xingye_shanxin: 'XYSX',
  bobai_shuiming: 'BBSM',
  yulin: 'YL',
  yulin_datang: 'YLDT',
  beiliu: 'BL',
  beiliu_liumadawang: 'BLLM',
  rongxian: 'RX',
  rongxian_shitou: 'RXST',
  wudong: 'WD',
  xinxu: 'XXU',
  yongning: 'YNNG',
  nanning: 'NN',
  nanning_tingzi: 'NNTZ',
  hengxian: 'HX',
  hengzhou: 'HZ',
  binyang: 'BY',
  yizhou: 'YZ',
  rongshui: 'RS',
  rongan_changan: 'RACA',
  sanjiang_guyi: 'SJGY',
  sanjiang_guyihuangpai: 'SJGYP',
  sanjiang_chengcun: 'SJCC',
  yangshuo_xingpingxinganzhou: 'YSXP',
  lingui_wutong: 'LGWT',
  lingui_huangsha: 'LGHS',
  baise_youjiang: 'BSYJ',
  longzhou: 'LZ',
  hekou: 'HKOU',
  yangjiang: 'YJ',
  yangchun_heshui: 'YCHS',
  yangchun_tanshui: 'YCTS',
  yangchun_shuangjiao: 'YCSJ',
  yangchun_hekou: 'YCHK',
  yangdong: 'YD',
  maoming: 'MM',
  maoming_malan: 'MMML',
  gaozhou: 'GZhou',
  suixi_suicheng: 'SXSC',
  suixi_caotan: 'SXCT',
  zhanjiang: 'ZJ',
  zhanjiang_potou: 'ZJPT',
  wuchuan: 'WC',
  huazhou_xiajiang: 'HZXJ',
  huazhou_shangjiang: 'HZSJ',
  beihai: 'BH',
  beihai_yingpan: 'BHYP',
  beihai_haibianhua: 'BHHB',
  qinzhou: 'QZ',
  fangchenggang: 'FCG',
  haining_hehui: 'HNHH',
  lingshan: 'LS',
  lingshan_taiping: 'LSTP',
  xiaojiang_fuwang: 'XJFW',
  pubei_fuwang: 'PBFW',
  lianzhou: 'LZhou',
  lianjiang_hailaohua: 'LJHL',
  sanya_maihua: 'SYMH',
  danzhou: 'DZhou',
  dongguan: 'DG',
  dongguan_tangjiao: 'DGTJ',
  dongguan_huangmaling: 'DGHM',
  zhuhai: 'ZH',
  zhuhai_doumen: 'ZHDM',
  shenzhen: 'SZ',
  liannan_zhaigang: 'LNZG',
  shaoguan: 'SG',
  hezhou: 'HZhou',
  usa_san_francisco: 'USSF',
  usa_new_york: 'USNY',
  usa_los_angeles: 'USLA',
  canada_vancouver: 'CAVC',
  canada_toronto: 'CATO',
  australia_sydney: 'AUSY',
  australia_melbourne: 'AUMB',
  newzealand_auckland: 'NZAK',
  uk_london: 'UKLN',
  singapore: 'SGAP',
  malaysia_kualalumpur: 'MYKL',
  malaysia_penang: 'MYPE',
  vietnam_hochiminh: 'VNHCM',
  thailand_bangkok: 'THBK',
  other: 'OT'
}

/** Jyutjyu 地區代碼（region_code） → 方言代碼 */
export const REGION_CODE_TO_DIALECT_ID: Record<string, DialectId> = Object.fromEntries(
  Object.entries(DIALECT_REGION_CODES).map(([id, code]) => [code, id as DialectId])
) as Record<string, DialectId>

/** 根據 Jyutjyu 的 region_code 取顯示名稱（香港繁體）；未知則回傳原值 */
export function getDialectLabelByRegionCode(regionCode: string): string {
  const code = String(regionCode || '').trim().toUpperCase()
  if (!code) return ''
  const id = REGION_CODE_TO_DIALECT_ID[code]
  return id ? DIALECT_LABELS[id] : code
}

/** 用於下拉的選項：{ value, label } */
export const DIALECT_OPTIONS = DIALECT_IDS.map((id) => ({
  value: id,
  label: DIALECT_LABELS[id]
}))

/** 根據代碼取顯示名稱 */
export function getDialectLabel(id: string): string {
  return DIALECT_LABELS[id as DialectId] ?? id
}

const COLOR_PALETTE = ['blue', 'green', 'teal', 'orange', 'amber', 'yellow', 'purple', 'pink', 'indigo', 'cyan', 'red', 'gray'] as const

/** 方言對應的 UBadge 顏色（用於審核頁等） */
export const DIALECT_COLORS: Record<DialectId, string> = Object.fromEntries(
  DIALECT_IDS.map((id, i) => [id, id === 'other' ? 'gray' : COLOR_PALETTE[i % (COLOR_PALETTE.length - 1)]])
) as Record<DialectId, string>

export function getDialectColor(id: string): string {
  return DIALECT_COLORS[id as DialectId] ?? 'gray'
}
